image:
  tag: 1.18.2

service:
  listen:
    type: LoadBalancer

persistence:
  data:
    enabled: true
    mountPath: /var/syncthing
    accessMode: ReadWriteOnce
    storageClass: local-path
    size: 10Gi